-------------------------------------------------
-- author: Seilscheibe RDA
-- date: 29/08/21
-- filename: exampleTable.lua
-- notes: open-surce - visible
-------------------------------------------------
